---
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: postgresqlinstances.database.example.org
spec:
  definitionRef:
    name: postgresqlinstances.database.example.org
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.oam.dev/aggregate-to-controller: "true"
  name: oam:claim:postgresqlinstancesdatabase.example.org:aggregate-to-controller
rules:
- apiGroups:
  - database.example.org
  resources:
  - postgresqlinstances
  verbs:
  - '*'
